### ISSUE TITLE
We cannot build the site to Netlify

### ISSUE THREAD

**Issue by fsuaterdogan** [CrystallizeAPI/crystallize-nextjs-boilerplate#91] opened 2021-02-20 14:33 UTC
Hello, when trying to build the site to Netlify we get the following error:

```
5:27:03 PM: Error occurred prerendering page "/en". Read more: https://err.sh/next.js/prerender-error
5:27:03 PM: ReferenceError: window is not defined
5:27:03 PM:     at /opt/build/repo/node_modules/imsc/src/main/js/html.js:1725:53
5:27:03 PM:     at Object.<anonymous> (/opt/build/repo/node_modules/imsc/src/main/js/html.js:1742:3)
5:27:03 PM:     at Module._compile (internal/modules/cjs/loader.js:1138:30)
5:27:03 PM:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
5:27:03 PM:     at Module.load (internal/modules/cjs/loader.js:986:32)
5:27:03 PM:     at Function.Module._load (internal/modules/cjs/loader.js:879:14)
5:27:03 PM:     at Module.require (internal/modules/cjs/loader.js:1026:19)
5:27:03 PM:     at require (internal/modules/cjs/helpers.js:72:18)
5:27:03 PM:     at Object.<anonymous> (/opt/build/repo/node_modules/imsc/src/main/js/main.js:29:22)
5:27:03 PM:     at Module._compile (internal/modules/cjs/loader.js:1138:30)
5:27:03 PM: Error: {"message":"Tenant undefined does not exist.","errorCode":0,"traceId":"d42e452d-bdee-4cb5-b8d0-bc022baafa6f"}
5:27:03 PM:     at simplyFetchFromGraph (/opt/build/repo/.next/server/pages/_app.js:1508:11)
5:27:03 PM:     at processTicksAndRejections (internal/process/task_queues.js:97:5)
5:27:03 PM:     at async Function.module.exports.IlR1.MyApp.getInitialProps (/opt/build/repo/.next/server/pages/_app.js:1242:9)
5:27:03 PM:     at async loadGetInitialProps (/opt/build/repo/node_modules/next/dist/next-server/lib/utils.js:5:91)
5:27:03 PM:     at async renderToHTML (/opt/build/repo/node_modules/next/dist/next-server/server/render.js:25:1484)
5:27:03 PM:     at async /opt/build/repo/node_modules/next/dist/export/worker.js:26:6
5:27:03 PM:     at async /opt/build/repo/node_modules/next/dist/build/tracer.js:3:470
5:27:03 PM: Could not fetch common page data
5:27:03 PM: Error: {"message":"Tenant undefined does not exist.","errorCode":0,"traceId":"4133802a-8fc0-4625-a959-d1a57e353642"}
5:27:03 PM:     at simplyFetchFromGraph (/opt/build/repo/.next/server/pages/_app.js:1508:11)
5:27:03 PM:     at processTicksAndRejections (internal/process/task_queues.js:97:5)
5:27:03 PM:     at async Function.module.exports.IlR1.MyApp.getInitialProps (/opt/build/repo/.next/server/pages/_app.js:1242:9)
5:27:03 PM:     at async loadGetInitialProps (/opt/build/repo/node_modules/next/dist/next-server/lib/utils.js:5:91)
5:27:03 PM:     at async renderToHTML (/opt/build/repo/node_modules/next/dist/next-server/server/render.js:25:1484)
5:27:03 PM:     at async /opt/build/repo/node_modules/next/dist/export/worker.js:26:6
5:27:03 PM:     at async /opt/build/repo/node_modules/next/dist/build/tracer.js:3:470
5:27:03 PM: Could not fetch common page data
5:27:03 PM: info  - Generating static pages (3/3)
5:27:03 PM: > Build error occurred
5:27:03 PM: Error: Export encountered errors on following paths:
5:27:03 PM: 	/en
5:27:03 PM:     at /opt/build/repo/node_modules/next/dist/export/index.js:30:1103
5:27:03 PM:     at async /opt/build/repo/node_modules/next/dist/build/tracer.js:3:470
5:27:03 PM:     at async /opt/build/repo/node_modules/next/dist/build/index.js:39:69
5:27:03 PM:     at async /opt/build/repo/node_modules/next/dist/build/tracer.js:3:470
5:27:03 PM:     at async /opt/build/repo/node_modules/next/dist/build/index.js:21:731
5:27:03 PM:     at async /opt/build/repo/node_modules/next/dist/build/tracer.js:3:470
5:27:03 PM: npm ERR! code ELIFECYCLE
5:27:03 PM: npm ERR! errno 1
5:27:03 PM: npm ERR! crystallize-nextjs-boilerplate@7.0.1 build: `next build`
5:27:03 PM: npm ERR! Exit status 1
5:27:03 PM: npm ERR!
5:27:03 PM: npm ERR! Failed at the crystallize-nextjs-boilerplate@7.0.1 build script.
5:27:03 PM: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
5:27:03 PM: npm ERR! A complete log of this run can be found in:
5:27:03 PM: npm ERR!     /opt/buildhome/.npm/_logs/2021-02-20T14_27_03_484Z-debug.log
```

Can you help me? Thanks

**Comment by hakonkrogh** [comment] 2021-03-03 09:02
Duplicate of #92

**Closed by hakonkrogh** 2021-03-03 09:02 UTC
